### ISSUE TITLE
What type if ActiveDocument property?

### ISSUE THREAD

**Issue by gep13** [RickStrahl/Snippets-MarkdownMonster-Addin#1]
@RickStrahl  Is it possible to just get the file name without the path and extension?

This is what I currently have in my snippet (based on a file called `this-is-a-test.md`)

```
---
Title: {{System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(Model.ActiveDocument.Filename.Replace('-', ' '))}}
Tags:
- 
---
```

Which results in the following:

![image](https://cloud.githubusercontent.com/assets/1271146/22107392/629f9c28-de45-11e6-8eba-153a89ca52a7.png)

So, quite close to what I am looking for 😄

**Comment by RickStrahl** [comment]
Like this?

```
---
Title: {{System.Globalization.CultureInfo.CurrentCulture.TextInfo.ToTitleCase(System.IO.Path.GetFileNameWithoutExtension(Model.ActiveDocument.Filename).Replace('-', ' '))}}
Tags:
- 
---
```

**Comment by RickStrahl** [comment]
Ok... I made a few more changes to the @Razor hosting part that now allows adding assemblies and namespaces.

This is what you want:

```
@reference Westwind.Utilities.dll
@using Westwind.Utilities
@{
    var file = Path.GetFileNameWithoutExtension(Model.ActiveDocument.Filename);
    
    file = StringUtils.FromCamelCase(file);
    file = file.Replace("-"," ");
}---
Title: @file
Timestamp: @DateTime.Now.ToString("MMM dd, yyyy HH:mm")
Tags:
-
---
```

FWIW, the first two lines will not be necesary any more as I'm adding those as default dependencies.

You'll need to make sure you grab 1.10 of the addin though - update and restart.

**Comment by gep13** [comment]
@RickStrahl thank you very much!  This is perfect!

I modified it slightly:

```csharp
@{
    var file = Path.GetFileNameWithoutExtension(Model.ActiveDocument.Filename);
    
    file = file.Replace("-"," ");
    file = StringUtils.ProperCase(file);
}---
Title: @file
Timestamp: @DateTime.Now.ToString("MMM dd, yyyy HH:mm")
Tags:
-
---
```
